
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yoan
 */
public class peminjam extends javax.swing.JFrame {

    
    public peminjam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtjudul = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rdk = new javax.swing.JRadioButton();
        rdbk = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_peminjam = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtkembali = new com.toedter.calendar.JDateChooser();
        txtpinjam = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        pelajaran = new javax.swing.JRadioButton();
        novel = new javax.swing.JRadioButton();
        komik = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        jLabel1.setText("No. Anggota");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 90, 90, 18);

        txtno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtno);
        txtno.setBounds(40, 110, 160, 30);

        jLabel2.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        jLabel2.setText("Alamat");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 210, 100, 18);
        getContentPane().add(txtnama);
        txtnama.setBounds(40, 170, 160, 30);

        txtjudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjudulActionPerformed(evt);
            }
        });
        getContentPane().add(txtjudul);
        txtjudul.setBounds(40, 440, 160, 30);

        jLabel3.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        jLabel3.setText("Judul Buku");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 340, 100, 18);

        jLabel4.setFont(new java.awt.Font("Swis721 Hv BT", 1, 24)); // NOI18N
        jLabel4.setText("Daftar Peminjaman dan Pengembalian Buku");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 20, 650, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 62, 1070, 10);

        jLabel5.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        jLabel5.setText("Tanggal Peminjam");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 480, 140, 18);

        jLabel6.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        jLabel6.setText("Status");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 600, 160, 18);

        buttonGroup1.add(rdk);
        rdk.setText("Kembali");
        rdk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdkActionPerformed(evt);
            }
        });
        getContentPane().add(rdk);
        rdk.setBounds(40, 620, 150, 23);

        buttonGroup1.add(rdbk);
        rdbk.setText("Belum Kembali");
        rdbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbkActionPerformed(evt);
            }
        });
        getContentPane().add(rdbk);
        rdbk.setBounds(40, 650, 160, 23);

        jLabel7.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal Pengembalian");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 540, 160, 18);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(300, 60, 50, 10);

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane1.setViewportView(txtalamat);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 240, 166, 96);

        jLabel8.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        jLabel8.setText("Nama");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 150, 100, 18);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(270, 60, 50, 10);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(260, 70, 50, 10);

        t_peminjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No. Anggota", "Nama Peminjam", "Alamat ", "Jenis Buku", "Judul Buku", "Tanggal Pinjam", "Tanggal Kembali", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(t_peminjam);
        if (t_peminjam.getColumnModel().getColumnCount() > 0) {
            t_peminjam.getColumnModel().getColumn(0).setResizable(false);
            t_peminjam.getColumnModel().getColumn(1).setResizable(false);
            t_peminjam.getColumnModel().getColumn(2).setResizable(false);
            t_peminjam.getColumnModel().getColumn(3).setResizable(false);
            t_peminjam.getColumnModel().getColumn(4).setResizable(false);
            t_peminjam.getColumnModel().getColumn(5).setResizable(false);
            t_peminjam.getColumnModel().getColumn(6).setResizable(false);
            t_peminjam.getColumnModel().getColumn(7).setResizable(false);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(240, 150, 810, 500);

        jButton1.setText("Print");
        getContentPane().add(jButton1);
        jButton1.setBounds(750, 100, 100, 30);

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 100, 100, 30);

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(450, 100, 100, 30);

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(590, 100, 100, 30);
        getContentPane().add(txtkembali);
        txtkembali.setBounds(40, 570, 160, 30);
        getContentPane().add(txtpinjam);
        txtpinjam.setBounds(40, 510, 160, 30);

        jLabel9.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        jLabel9.setText("Judul Buku");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 420, 100, 18);

        buttonGroup2.add(pelajaran);
        pelajaran.setText("Pelajaran");
        getContentPane().add(pelajaran);
        pelajaran.setBounds(110, 380, 93, 23);

        buttonGroup2.add(novel);
        novel.setText("Novel");
        getContentPane().add(novel);
        novel.setBounds(40, 360, 53, 23);

        buttonGroup2.add(komik);
        komik.setText("Komik");
        komik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komikActionPerformed(evt);
            }
        });
        getContentPane().add(komik);
        komik.setBounds(40, 390, 53, 23);

        setBounds(0, 0, 1086, 721);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoActionPerformed

    private void txtjudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjudulActionPerformed

    private void rdkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdkActionPerformed

    private void rdbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbkActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       txtno.setText("");
       txtnama.setText("");
       txtalamat.setText("");
       txtjudul.setText("");
       buttonGroup1.clearSelection();
       txtpinjam.setDate(null);
       txtkembali.setDate(null);
       buttonGroup2.clearSelection();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-ddd");
        String Pinjam = dateFormat.format(txtpinjam.getDate());
        String Kembali = dateFormat.format(txtkembali.getDate());
        if ("".equals(txtno.getText()) || "".equals(txtnama.getText()) || "".equals(txtalamat.getText()) || Pinjam.equals("")  || Kembali.equals("")) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else{
            String ST = "";
            String JB = "";
            if (rdk.isSelected()) {
                ST = "Kembali";
            }else{
                ST = "Belum Kembali";
            }
            if (pelajaran.isSelected()) {
                JB = "pelajaran";
            }else if(novel.isSelected()){
                JB = "novel";
            }else{
                JB = "komik";
            }
                    
            String SQL = "INSERT INTO `tb_pinjam`(`No`, `nama`, `alamat`, `jenis_buku`, `judul`, `pinjam`, `kembali`, `status')"
                    + "VALUES('"+txtno.getText()
                    +"','"+txtnama.getText()
                    +"','"+txtalamat.getText()
                    +"','"+JB
                    +"','"+txtjudul.getText()+"','"+Pinjam
                    +"','"+Kembali
                    +"','"+ST+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void komikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_komikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new peminjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton komik;
    private javax.swing.JRadioButton novel;
    private javax.swing.JRadioButton pelajaran;
    private javax.swing.JRadioButton rdbk;
    private javax.swing.JRadioButton rdk;
    private javax.swing.JTable t_peminjam;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtjudul;
    private com.toedter.calendar.JDateChooser txtkembali;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtno;
    private com.toedter.calendar.JDateChooser txtpinjam;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"No.Anggota","Nama Peminjam","Alamat","Jenis Buku","Judul Buku","Tanggal Pinjam","Tanggal Kembali","Status"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_pinjam";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while (rs.next()) {
                String No = rs.getString(1);
                String  nama = rs.getString(2);
                String alamat = rs.getString(3);
                String jenis_buku = "";
                if ("pelajaran".equals(rs.getString(4))) {
                    jenis_buku = "pelajaran";
                } else if("novel".equals(rs.getString(4))){
                    jenis_buku = "novel";
                }else{
                    jenis_buku = "komik";
                }
                String judul = rs.getString(5);
                String pinjam = rs.getString(6);
                String kembali = rs.getString(7);
                String status = "";
                if ("kembali".equals(rs.getString(8))){
                    status = "kembali";
                }else{
                    status = "belum kembali";
                }
                
                String data[] = {No,nama,jenis_buku,judul,pinjam,kembali,status};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(peminjam.class.getName()).log(Level.SEVERE, null, ex);
        }
        t_peminjam.setModel(dtm);
    }
}
